### PR TITLE
[enhancement] Generics

### PR DESCRIPTION
**Pull request by mitghi**
This PR adds support for generics.

### CODE REVIEW

**Comment by metalmatze** [comment]
Very nice changes.
I'm wondering, is this backward compatible? It probably needs a v2, right?

**Comment by mitghi** [comment]
Thanks, I think yes, it needs v2.

**Comment by MichaelMure** [comment]
It's not, you can't use the generic struct without giving the types. It makes a lot of sense though, would love to have a V2 with that.

**Comment by mitghi** [comment]
> It's not, you can't use the generic struct without giving the types. It makes a lot of sense though, would love to have a V2 with that.

Sorry, I have corrected the reply. I meant that it needs v2.

**Comment by MichaelMure** [comment]
FYI, there is a downside to that generic version: key types needs to be `comparable`, which crucially leave out any interface types. I think it's really a golang limitation (you can use interface types as key with a normal map, why not when it's generic?) but that's an important point.

**Comment by MichaelMure** [comment]
FYI, I'm close to use that in production. It'd be nice to have a proper version, otherwise I'll have to fork it somehow to avoid having `replace` directive everywhere.

**Comment by mitghi** [comment]
I have added v2.0.0 release to my fork. I would suggest to use that if you see it fit until this PR gets merged.

@tidwall What would be your suggestions about this PR?

**Comment by tidwall** [comment]
I haven't had a chance to take a deep dive into the PR, but one cursory concern is that using `comparable` may break compatibility because the current version uses interface keys. I think this is the same thing that @MichaelMure ran into.

I would prefer not to bump the version to v2 if we can avoid it.

Perhaps we can create a new type, such as `tinylru.Map` or `tinylru.LRUG`?

That's what I did with my [btree](https://github.com/tidwall/btree) and [rtree](https://github.com/tidwall/rtree) and it seemed to work out.

**Comment by MichaelMure** [comment]
FYI, golang 1.20 fix that `comparable` problem:
> [Comparable types](https://tip.golang.org/ref/spec#Comparison_operators) (such as ordinary interfaces) may now satisfy comparable constraints, even if the type arguments are not strictly comparable (comparison may panic at runtime). This makes it possible to instantiate a type parameter constrained by comparable (e.g., a type parameter for a user-defined generic map key) with a non-strictly comparable type argument such as an interface type, or a composite type containing an interface type.

> Perhaps we can create a new type, such as tinylru.Map or tinylru.LRUG?

`tinylru.LRUG` looks reasonable to me.

In any case, a properly merged/tagged version would be great, I'm getting a bit tired to carry a `replace` in my `go.mod` files :-|

**Pull request merged**
